" ------------------------------------------------------------------------------
" Basic configuration
" ------------------------------------------------------------------------------
set noswapfile
set nobackup
set nowb
set pastetoggle=<F2>
set undolevels=1000
set wildignore=*.o,*~,*.swp,*.bak,*.pyc,*.class
set wildignore+=*/.git/*,*/.hg/*,
set title
set noshowmode
set visualbell
set noerrorbells
set encoding=utf-8
set nocompatible
set number
set relativenumber
set t_vb=
set tm=500
set hid
set autoread
au FocusGained,BufEnter * checktime
set whichwrap+=<,>,h,l
set lazyredraw

" ------------------------------------------------------------------------------
" Shortcuts
" ------------------------------------------------------------------------------
let mapleader=','
nnoremap <leader>w :w!<cr>
nnoremap <leader>rc :so $MYVIMRC<CR>
map <silent> <leader><cr> :noh<cr>
command W :execute ':silent w !sudo tee % > /dev/null' | :edit!
command Wq :execute ':W' | :q
command WQ :Wq

" ------------------------------------------------------------------------------
" Filetypes configuration
" ------------------------------------------------------------------------------
set expandtab
autocmd FileType make set noexpandtab
autocmd FileType automake set noexpandtab
autocmd FileType fstab set noexpandtab
autocmd FileType c set noexpandtab
set shiftwidth=4
set tabstop=4
autocmd FileType c set shiftwidth=8
autocmd FileType c set tabstop=8
autocmd FileType json set shiftwidth=2
autocmd FileType json set tabstop=2
set lbr
set tw=80
set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

" ------------------------------------------------------------------------------
" Load plugins/color schemes
" ------------------------------------------------------------------------------
source ~/.vim/plugins.vim

" ------------------------------------------------------------------------------
" Color and graphics
" ------------------------------------------------------------------------------
syntax on
if exists("$TMUX")
    " We need those overrides for VIM to work
    " correctly in tmux 24bit mode
    let &t_8f = "\<Esc>[38:2:%lu:%lu:%lum"
    let &t_8b = "\<Esc>[48:2:%lu:%lu:%lum"
endif
highlight Normal ctermbg=NONE guibg=NONE
highlight NonText ctermbg=NONE guibg=NONE
set termguicolors
try
    colorscheme onedark
catch
endtry
set list
set numberwidth=5

" ------------------------------------------------------------------------------
" Search and replace
" ------------------------------------------------------------------------------
set ignorecase
set smartcase
set showmatch
set hlsearch
set incsearch
